MeneelySIGCSE2009_wordfreq = 
[ [ 'project', 116 ],
  [ 'student', 55 ],
  [ 'course', 49 ],
  [ 'open-source', 39 ],
  [ 'software', 38 ],
  [ 'test', 32 ],
  [ 'required', 30 ],
  [ 'rose', 27 ],
  [ 'use', 26 ],
  [ 'educators', 21 ],
  [ 'repository', 21 ],
  [ 'code', 20 ],
  [ 'assigned', 14 ],
  [ 'automated', 14 ],
  [ 'engineering', 14 ],
  [ 'other', 14 ],
  [ 'develop', 13 ],
  [ 'iTrust', 13 ],
  [ 'learn', 13 ],
  [ 'provide', 13 ],
  [ 'artifacts', 12 ],
  [ 'class', 12 ],
  [ 'computer', 12 ],
  [ 'contribute', 12 ],
  [ 'experience', 12 ],
  [ 'work', 12 ],
  [ 'education-friendly', 11 ],
  [ 'science', 11 ],
  [ 'such', 11 ],
  [ 'all', 10 ],
  [ 'manage', 10 ] ]
