[ [ 'vulnerability', 58 ],
  [ 'software', 55 ],
  [ 'example', 46 ],
  [ 'secure', 43 ],
  [ 'votd', 40 ],
  [ 'developed', 25 ],
  [ 'demonstrate', 21 ],
  [ 'student', 21 ],
  [ 'code', 19 ],
  [ 'relevant', 18 ],
  [ 'class', 16 ],
  [ 'course', 16 ],
  [ 'engineer', 16 ],
  [ 'each', 15 ],
  [ 'principle', 13 ],
  [ 'large', 12 ],
  [ 'project', 12 ],
  [ 'Engineer', 11 ],
  [ 'other', 11 ],
  [ 'simple', 11 ],
  [ 'use', 11 ],
  [ 'Overflow', 10 ],
  [ 'design', 10 ],
  [ 'historical', 10 ] ]
