[ [ 'jazz', 70 ],
  [ 'sangam', 49 ],
  [ 'pair', 45 ],
  [ 'develop', 33 ],
  [ 'program', 33 ],
  [ 'code', 26 ],
  [ 'distributed', 25 ],
  [ 'use', 23 ],
  [ 'feature', 22 ],
  [ 'team', 21 ],
  [ 'collaboration', 19 ],
  [ 'integrate', 17 ],
  [ 'work', 17 ],
  [ 'change', 16 ],
  [ 'control', 13 ],
  [ 'platform', 13 ],
  [ 'like', 12 ],
  [ 'tool', 12 ],
  [ 'source', 11 ],
  [ 'workspace', 11 ],
  [ 'driver', 10 ],
  [ 'student', 10 ] ]
